autodeploy/apps/operation/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps import operation
from autodeploy.apps.operation import views
from autodeploy.apps.operation.views import ListOperationView, DeleteOperationView, DetailOperationView, \
    get_operation_list

logger = logging.getLogger(__name__)
app_name = 'operation'
urlpatterns = [
    url(r'detail/(?P<pk>\d{1,10})/$', DetailOperationView.as_view(), name='detail'),
    url(r'list/$', ListOperationView.as_view(), name='list'),
    url(r'websocket/$',get_operation_list,name='sm_list'),
    url(r'delete/(?P<oid>\d{1,10})/$', DeleteOperationView.as_view(), name='delete'),
]

autodeploy/apps/playbooks/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.playbooks.views import DetailPlayBookView, ListPlayBooksView, EditorPlayBookView, PlayBooksView, \
    DeletePlayBooksView, ListBookFileView, EditorBookFileView, DeleteBookFileView, ReplayPlayBooksView, \
    VersionIsExistView

logger = logging.getLogger(__name__)
app_name = 'playbooks'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'file/list/$', ListBookFileView.as_view(), name='file_list'),
    url(r'list/$', ListPlayBooksView.as_view(), name='list'),
    url(r'file/editor/(?P<fid>\d{1,10})?/?$', EditorBookFileView.as_view(), name='file_editor'),
    url(r'editor/(?P<pbid>\d{1,10})?/?$', EditorPlayBookView.as_view(), name='editor'),
    
    url(r'detail/(?P<pk>\d{1,10})?/?$', DetailPlayBookView.as_view(), name='detail'),
    url(r'file/delete/(?P<fid>\d{1,10})?/?$', DeleteBookFileView.as_view(), name='file_delete'),
    url(r'delete/(?P<pbid>\d{1,10})?/?$', DeletePlayBooksView.as_view(), name='delete'),
    url(r'run/$', PlayBooksView.as_view(), name='run'),
    url(r'replay/$', ReplayPlayBooksView.as_view(), name='replay'),#日志重新运行剧本
    url(r'version/is_exist/$', VersionIsExistView.as_view(), name='version_is_exist'),#剧本版本是否存在

]

autodeploy/apps/server/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.server.views import ListServerView, EditorServerView, DetailServerView, DeleteServerView, \
    DeletePlayBooksRelationView, ListServerManageView, EditorServerManageView, DetailServerManageView, \
    DeleteServerManageView, AutoCompleteManageListView

logger = logging.getLogger(__name__)
app_name = 'server'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'manage/list/$', ListServerManageView.as_view(), name='manage_list'),
    url(r'manage/editor/(?P<smid>\d{1,10})?/?$', EditorServerManageView.as_view(), name='manage_editor'),
    url(r'manage/detail/(?P<pk>\d{1,10})?/?$', DetailServerManageView.as_view(), name='manage_detail'),
    url(r'manage/delete/(?P<smid>\d{1,10})?/?$', DeleteServerManageView.as_view(), name='manage_delete'),

    url(r'list/$', ListServerView.as_view(), name='list'),
    url(r'editor/(?P<sid>\d{1,10})?/?$', EditorServerView.as_view(), name='editor'),
    url(r'autocomplete/$', AutoCompleteManageListView.as_view(), name='autocomplete'),
    url(r'detail/(?P<pk>\d{1,10})/$', DetailServerView.as_view(), name='detail'),
    url(r'delete/(?P<sid>\d{1,10})/$', DeleteServerView.as_view(), name='delete'),
    url(r'delete/relation/$', DeletePlayBooksRelationView.as_view(), name='delete_relation'),
]

autodeploy/urls.py
# -*- coding: utf-8 -*-
"""autodeploy URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import django
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from autodeploy import settings
from autodeploy.apps.index.views import IndexView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', include('autodeploy.apps.index.urls')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user/', include('autodeploy.apps.user.urls')),
    url(r'^server/', include('autodeploy.apps.server.urls')),
    url(r'^playbooks/', include('autodeploy.apps.playbooks.urls')),
    url(r'^operation/', include('autodeploy.apps.operation.urls')),
    url(r'^upload/', include('autodeploy.apps.common.upload_file.urls')),
]
# 加upload访问的配置
urlpatterns += [url(r'^upload/(?P<path>.*)$', django.views.static.serve,
                    {'document_root': settings.MEDIA_ROOT})]
if not settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }),
    ]

autodeploy/apps/operation/models.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.db import models

from autodeploy.apps.common.managers import DefaultManager
from autodeploy.apps.common.models import BaseModel
from autodeploy.apps.playbooks.models import PlayBooks
from autodeploy.apps.server.models import Server

logger = logging.getLogger(__name__)


class OperationLog(BaseModel):
    RESULT_STATUS = (('success', '成功'), ('defeat', '失败'))
    play_books = models.ForeignKey(PlayBooks, verbose_name='剧本', null=True, on_delete=models.SET_NULL)
    books_name = models.CharField(verbose_name="剧本名", blank=True, max_length=100, null=True)
    # content = models.CharField(verbose_name='操作内容', max_length=100)
    server = models.ForeignKey(Server, verbose_name='服务器', null=True, on_delete=models.SET_NULL)
    server_ip = models.CharField(verbose_name="ip", max_length=100, blank=True, null=True)
    # result = models.CharField(verbose_name='返回结果', max_length=1000)
    version = models.CharField(verbose_name='剧本版本', max_length=100, blank=True)
    status = models.CharField(verbose_name='状态', max_length=20, blank=True, choices=RESULT_STATUS, default='success')
    end_time = models.DateTimeField(verbose_name='剧本结束时间', null=True)
    objects = DefaultManager()
    objt = models.Manager()
    
    class Meta:
        db_table = 'operation_log'
        verbose_name = '操作日志记录'
        verbose_name_plural = '操作日志记录表'
        ordering = ['-id']


class OperationDetail(BaseModel):
    operation_log = models.ForeignKey(OperationLog, verbose_name='剧本日志')
    result = models.CharField(verbose_name='返回结果', max_length=1000)
    status = models.CharField(verbose_name='结果状态', max_length=1000, blank=True)

    class Meta:
        db_table = 'operation_detail'
        verbose_name = '操作返回记录'
        verbose_name_plural = '操作返回记录表'
        ordering = ['-id']

autodeploy/apps/operation/forms.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

logger = logging.getLogger(__name__)

autodeploy/apps/operation/views.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-24 上午9:43.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.models import model_to_dict
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import DetailView
from django.views.generic import View

from autodeploy.apps.common.search import SearchView
from autodeploy.apps.operation.models import OperationLog, OperationDetail
from autodeploy.apps.server.models import Server

logger = logging.getLogger(__name__)


def create_log(operation_log, result, detail_status,status=None):
    if status == 'defeat':
        operation_log.status = status
        operation_log.save()
    try:
        OperationDetail.objects.create(operation_log=operation_log,
                                       result=result,status=detail_status)
    except Exception as e:
        logger.error('运行错误:%s' % e)
        return False
    return True


class ListOperationView(LoginRequiredMixin, SearchView):
    """获取日志列表"""
    template_name = 'operation/list.html'
    model = OperationLog
    context_object_name = 'operation_list'
    name_list = ['version', 'server_ip', 'books_name']
    
    def get_context_data(self, **kwargs):
        context = super(ListOperationView, self).get_context_data(**kwargs)
        server = self.get_server()
        status_tuple = OperationLog.RESULT_STATUS
        status = self.request.GET.get('status', '')
        self.status_show = '全部'
        queryset = self.search()
        if status:
            for t in status_tuple:
                if t[0] == status:
                    self.status_show = t[1]
        if server:
            context[self.context_object_name] = queryset.filter(server=server)
            context['server'] = server
        else:
            context['server'] = None
            context[self.context_object_name] = queryset
        context['status_show'] = self.status_show
        context['status_tuple'] = status_tuple
        context['status'] = status
        return context
    
    def get_server(self):
        sid = self.request.GET.get('sid')
        try:
            server = Server.objects.get(pk=sid)
        except Exception as e:
            logger.error('不存在该服务器,错误:%s' % e)
            server = None
        return server


class DetailOperationView(LoginRequiredMixin, DetailView):
    """日志详情"""
    template_name = 'operation/detail.html'
    model = OperationLog
    context_object_name = 'detail_list'
    
    def get_context_data(self, **kwargs):
        context = super(DetailOperationView, self).get_context_data(**kwargs)
        context[self.context_object_name] = self.get_object().operationdetail_set.filter()
        context['operation_log'] = self.get_object()
        return context


class DeleteOperationView(LoginRequiredMixin, View):
    """删除日志"""
    
    def get(self, request, *args, **kwargs):
        result = 0  # 0是删除失败
        try:
            oid = self.kwargs.get('oid', None)
            operation = OperationLog.objects.get(pk=oid)
            result = operation.update_delete()
            logger.info(u'%s删除日志成功%s' % (request.user, oid))
        except Exception as e:
            logger.error(u'删除日志出错,错误信息:%s' % e)
        
        return HttpResponse(result)


# @require_websocket
def get_operation_list(request):
    result = {'code': 0, 'operation_list': []}
    operation_list = OperationLog.objects.filter()[:10]
    for operation in operation_list:
        operation_dir = model_to_dict(operation)
        if operation_dir['end_time']:
            operation_dir['end_time'] = operation_dir['end_time'].strftime('%Y-%m-%d %H:%M:%S')
        else:
            operation_dir['end_time'] = ''
        operation_dir['create_time'] = operation.create_time.strftime('%Y-%m-%d %H:%M:%S')
        if operation.books_name:
            operation_dir['play_book_name'] = operation.books_name
        else:
            operation_dir['play_book_name'] = '更新'
            operation_dir['play_books'] = '更新'
        result['operation_list'].append(operation_dir)
    result['operation_list'].reverse()
    result['code'] = 1
    # result = json.dumps(result)
    # if request.is_websocket():
    #     request.websocket.send(result)
        # import uwsgi
        # uwsgi.websocket_handshake()
        # # import uwsgi
        # uwsgi.websocket_send(result)
    # else:
    return JsonResponse(result)
# def application(env, start_response):
#     # complete the handshake
#     uwsgi.websocket_handshake(env['HTTP_SEC_WEBSOCKET_KEY'], env.get('HTTP_ORIGIN', ''))
#     while True:
#         msg = uwsgi.websocket_recv()
#         uwsgi.websocket_send(msg)

autodeploy/apps/operation/templates/operation/detail.html
{% extends "base/base_width_left.html" %}
{% load pagination_tags %}

{% block flag %}log{% endblock %}
{% block path %}
    <a href="{% url 'operation:list'%}" title="" class="tip-bottom">日志列表</a>
    <a href="" title="" class="tip-bottom">日志详情查看</a>
{% endblock %}

{#{% block searchname %}searchaction{% endblock %}#}
{#{% block searchtip %}订单编号{% endblock %}#}

{% block container %}
    {{ block.super }}
        {% autopaginate detail_list 10%}
    {#    <ul class="nav nav-tabs">#}
    {#        <li role="presentation" class="active"><a href="{% url 'product:product_list' %}">订单</a></li>#}
    {#        <li role="presentation"><a href="{% url 'product:type_list' %}">分 类</a></li>#}
    {#        <li role="presentation"><a href="{% url 'product:theme_list' %}">主题</a></li>#}
    {#    </ul>#}
    <div hidediv="hide" class="table-responsive">
        <table class="table table-hover table-bordered ">
            <thead>
            <tr>
                <th>剧本名</th>
                <th>结果</th>
                <th>状态</th>
{#                <th>开始时间</th>#}
{#                <th>结束时间</th>#}
{#                <th>状态</th>#}
{#                <th>操作</th>#}
            </tr>
            </thead>
            {% for detail in detail_list %}
                <tr>
                    <td class="col-sm-2">
                        {% if detail.operation_log.play_books %}
                        {{ detail.operation_log.play_books.name }}
                        {% else %}
                            更新操作
                        {% endif %}
                    </td>
                    <td>
                        {{ detail.result }}
                    </td>
                    <td>
                        {{ detail.status }}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8"><p>没有查询到相关信息.</p></td>
                </tr>
            {% endfor %}
        </table>
     {% paginate %}
{#        <div class="pagination">#}
{#            <span class="step-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.prevous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{#                <span class="current">#}
{#                    page {{ page_obj.number }} of {{ paginator.num_pages }}.#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{##}
{#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}

    </div>
{% endblock %}
{% block footjs %}
    <script>

    </script>
{% endblock %}

autodeploy/apps/operation/templates/operation/list.html
{% extends "base/base_width_left.html" %}
{% load pagination_tags %}
{% block style %}
    <link rel="stylesheet" href="/static/bootstrap3_datetime/css/bootstrap-datetimepicker.css"/>
{% endblock %}
{% block flag %}log{% endblock %}
{% block path %}
    {% if server %}
        <a href="{% url 'server:detail' pk=server.id%}" title="" class="tip-bottom">{{ server.ip }}详情</a>
    {% endif %}
    <a href="" title="" class="tip-bottom">{% if server %}{{ server.ip }}日志查看{% else %}日志查看{% endif %}</a>
{% endblock %}

{#{% block searchname %}searchaction{% endblock %}#}
{#{% block searchtip %}订单编号{% endblock %}#}

{% block container %}
    {{ block.super }}
        {% autopaginate operation_list 10%}
    {#    <ul class="nav nav-tabs">#}
    {#        <li role="presentation" class="active"><a href="{% url 'product:product_list' %}">订单</a></li>#}
    {#        <li role="presentation"><a href="{% url 'product:type_list' %}">分 类</a></li>#}
    {#        <li role="presentation"><a href="{% url 'product:theme_list' %}">主题</a></li>#}
    {#    </ul>#}
    <div hidediv="hide" class="center-block">
        <form method="get" id="search_form">
            <input hidden value="" name="status" id="status"/>
            <input hidden value="{{ server.id }}" name="sid" id="status"/>
            <div class="dropdown" style="display:inline">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                                    aria-expanded="true">
                                {{ status_show }}
                                <span class="caret"></span>
                            </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation">
                        <a role="menuitem" tabindex="-1" href="{% if server.id %}{% url 'operation:list' %}?sid={{ server.id }}{% else %}{% url 'operation:list' %}{% endif %}">全部</a>
                    </li>
                    {% for status in status_tuple %}
                        <li role="presentation">
                            <a role="menuitem" tabindex="-1" status="{{  status.0  }}"
                               href="{% if server.id %}{% url 'operation:list' %}?sid={{ server.id }}&status={{ status.0 }}{% else %}{% url 'operation:list' %}?status={{ status.0 }}{% endif %}">{{ status.1 }}</a>
                        </li>
                    {% endfor %}
                </ul>

                <input class="input-sm" name="searchaction" placeholder="输入服务器ip/剧本名进行搜索"/>
                <div>
                    <div class="input-group date" id="start_time" style="width: 30%;float: left;">
                        <input class="form-control"  name="start_time" placeholder="开始时间">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <span style="float: left;font-size: 25px">----</span>
                    <div class="input-group date" id="end_time" style="width: 30%;float: left;">
                        <input class="form-control"  name="end_time" placeholder="结束时间">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <button type="button" class="btn btn-default" id="search_btn">搜索</button>
                    <div style="clear: both;"></div>
                </div>

            </div>
            {#        <a href="{% url 'product:product_form' %}" class="btn btn-primary">添 加</a>#}
        </form>
    </div>
    <div hidediv="hide" class="table-responsive">
        <form id="log_form" method="post">
        {% csrf_token %}
        <table class="table table-hover table-bordered ">
            <thead>
            <tr>
                <th>
                    <input type="checkbox" class="all">
                    <button class="btn btn-default run_re" type="button"
                               url="{% url 'playbooks:replay' %}">执行重载
                            </button>
                </th>
                <th>剧本名</th>
                <th>对应的服务器</th>
                <th>剧本版本</th>
                <th>开始时间</th>
                <th>结束时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            {% for operation in operation_list %}
                <tr>
                    <td>
                        <input type="checkbox" value="{{ operation.server.id }}" name="sid"/>
                    </td>
                    <td>
                        {% if operation.books_name %}
                        {{ operation.books_name }}
                            <input hidden type='checkbox' value="{{ operation.play_books.id }}" name="pbid"/>
                        {% else %}
                            更新操作
                            <input hidden type='checkbox' value="更新" name="pbid"/>
                        {% endif %}
                    </td>
                    <td>
                        {% if operation.server %}
                        {{ operation.server.ip }}

                        {% else %}
                        {{ operation.server_ip }}
                        {% endif %}
                    </td>
                    <td>
                        {% if operation.version %}
                        {{ operation.version }}
                           <input hidden type='checkbox' value="{{ operation.version }}" name="version"/>
                        {% else %}
                            未知
                            <input hidden type='checkbox' value="未知" name="version"/>
                        {% endif %}
                    </td>
{#                    <td>{{ operation.result }}</td>#}
                    <td>{{ operation.create_time|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ operation.end_time|date:'Y-m-d H:i:s' }}</td>
                    <td><span style="color:{% if operation.status == 'success' %}red{% endif %}">{{ operation.get_status_display }}</span></td>
                    <td>
                        <a class="btn btn-default btn-sm"
                                href="{% url 'operation:detail' pk=operation.id%} ">查看详情
                        </a>
                        <button type="button" class="btn btn-default btn-sm run" sid="{{ operation.server.id }}" version="{{ operation.version }}"
                                url="{% url 'playbooks:run'%}?pbid={{ operation.play_books.id }} ">重新执行
                        </button>
                        <button type="button" class="btn deletebtn btn-default btn-sm"
                                deleteurl="{% url 'operation:delete' oid=operation.id%} ">删除
                        </button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8"><p>没有查询到相关信息.</p></td>
                </tr>
            {% endfor %}
        </table>
     {% paginate %}
        </form>
{#        <div class="pagination">#}
{#            <span class="step-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.prevous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{#                <span class="current">#}
{#                    page {{ page_obj.number }} of {{ paginator.num_pages }}.#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{##}
{#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}

    </div>
{% endblock %}
{% block footjs %}
    <script type="text/javascript" src="/static/bootstrap3_datetime/js/moment.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap3_datetime/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
    <script type="text/javascript" src="/static/bootstrap3_datetime/js/bootstrap-datetimepicker.js"></script>
    <script>
        $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
                });
        //重新运行脚本
        $('.run').on('click',function(){
            var sid=$(this).attr('sid');
            var version=$(this).attr('version');
            var url=$(this).attr('url');
            $.post(url,{'sid':sid,'version':version},function(data){
                if(data==1){
                    alert("正在运行剧本");
                    time_lazy();
                }else{
                    alert('系统错误，无法运行')
                }
            })
        });
        $('.all').on('click', function () {
            if ($(this).is(':checked')) {
                $('td').find('input[name="sid"]').prop('checked', true);
                $('td').find('input[name="pbid"]').prop('checked', true);
                $('td').find('input[name="version"]').prop('checked', true);
                {#                alert($('td').find('input[name="sid"]').attr('checked'))#}
            } else {
                $('td').find('input[name="sid"]').removeAttr('checked');
                $('td').find('input[name="pbid"]').removeAttr('checked');
                $('td').find('input[name="version"]').removeAttr('checked');
            }
        });
        //批量重新运行脚本
        $('.run_re').on('click', function () {
            var $form = $('#log_form');
            if(is_server()){
                var url = $(this).attr('url');
                $.post(url, $form.serialize(), function (data) {
                    if (data == 1) {
                        alert('剧本已运行');
                        time_lazy()
                    } else {
                        alert('运行失败');
                    }
                })
            }else{
                alert('请选择一个日志！');
            }
        });
        function is_server(){
            var $sid_list=$("input[name='sid']");
            for(var i=0;i<$sid_list.length;i++){
                if($sid_list.eq(i).is(':checked')){
                    return true
                }
            }
            return false
        }
        $('input[name="sid"]').on('click',function(){
           if($(this).is(':checked')){
               $(this).parents('tr').find('input[name="pbid"]').prop('checked', true);
               $(this).parents('tr').find('input[name="version"]').prop('checked', true);
           }else{
               $(this).parents('tr').find('input[name="pbid"]').removeAttr('checked');
               $(this).parents('tr').find('input[name="version"]').removeAttr('checked');
           }
        });
    //时间控件
    $(function(){
        $('#start_time').datetimepicker({"pickSeconds":true,"format":"YYYY-MM-DD HH:mm:ss","language":"zh-Has","pickDate":true})
        $('#end_time').datetimepicker({"pickSeconds":true,"format":"YYYY-MM-DD HH:mm:ss","language":"zh-Has","pickDate":true})

    });
    $('#search_btn').on('click',function(){
        var status_show="{{ status_show }}";
        var $status_list=$(".dropdown-menu").find('li');
        for(var i=0;i<$status_list.length;i++){
            //alert($status_list.eq(i).find('a').text());
            if(String($status_list.eq(i).find('a').text())==status_show){
                $("#status").val($status_list.eq(i).find('a').attr('status'));
                $("#search_form").submit();
            }
        }
        $("#search_form").submit();
    });

    </script>
{% endblock %}