autodeploy/apps/operation/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps import operation
from autodeploy.apps.operation import views
from autodeploy.apps.operation.views import ListOperationView, DeleteOperationView, DetailOperationView, \
    get_operation_list

logger = logging.getLogger(__name__)
app_name = 'operation'
urlpatterns = [
    url(r'detail/(?P<pk>\d{1,10})/$', DetailOperationView.as_view(), name='detail'),
    url(r'list/$', ListOperationView.as_view(), name='list'),
    url(r'websocket/$',get_operation_list,name='sm_list'),
    url(r'delete/(?P<oid>\d{1,10})/$', DeleteOperationView.as_view(), name='delete'),
]

autodeploy/apps/playbooks/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.playbooks.views import DetailPlayBookView, ListPlayBooksView, EditorPlayBookView, PlayBooksView, \
    DeletePlayBooksView, ListBookFileView, EditorBookFileView, DeleteBookFileView, ReplayPlayBooksView, \
    VersionIsExistView

logger = logging.getLogger(__name__)
app_name = 'playbooks'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'file/list/$', ListBookFileView.as_view(), name='file_list'),
    url(r'list/$', ListPlayBooksView.as_view(), name='list'),
    url(r'file/editor/(?P<fid>\d{1,10})?/?$', EditorBookFileView.as_view(), name='file_editor'),
    url(r'editor/(?P<pbid>\d{1,10})?/?$', EditorPlayBookView.as_view(), name='editor'),
    
    url(r'detail/(?P<pk>\d{1,10})?/?$', DetailPlayBookView.as_view(), name='detail'),
    url(r'file/delete/(?P<fid>\d{1,10})?/?$', DeleteBookFileView.as_view(), name='file_delete'),
    url(r'delete/(?P<pbid>\d{1,10})?/?$', DeletePlayBooksView.as_view(), name='delete'),
    url(r'run/$', PlayBooksView.as_view(), name='run'),
    url(r'replay/$', ReplayPlayBooksView.as_view(), name='replay'),#日志重新运行剧本
    url(r'version/is_exist/$', VersionIsExistView.as_view(), name='version_is_exist'),#剧本版本是否存在

]

autodeploy/apps/server/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.server.views import ListServerView, EditorServerView, DetailServerView, DeleteServerView, \
    DeletePlayBooksRelationView, ListServerManageView, EditorServerManageView, DetailServerManageView, \
    DeleteServerManageView, AutoCompleteManageListView

logger = logging.getLogger(__name__)
app_name = 'server'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'manage/list/$', ListServerManageView.as_view(), name='manage_list'),
    url(r'manage/editor/(?P<smid>\d{1,10})?/?$', EditorServerManageView.as_view(), name='manage_editor'),
    url(r'manage/detail/(?P<pk>\d{1,10})?/?$', DetailServerManageView.as_view(), name='manage_detail'),
    url(r'manage/delete/(?P<smid>\d{1,10})?/?$', DeleteServerManageView.as_view(), name='manage_delete'),

    url(r'list/$', ListServerView.as_view(), name='list'),
    url(r'editor/(?P<sid>\d{1,10})?/?$', EditorServerView.as_view(), name='editor'),
    url(r'autocomplete/$', AutoCompleteManageListView.as_view(), name='autocomplete'),
    url(r'detail/(?P<pk>\d{1,10})/$', DetailServerView.as_view(), name='detail'),
    url(r'delete/(?P<sid>\d{1,10})/$', DeleteServerView.as_view(), name='delete'),
    url(r'delete/relation/$', DeletePlayBooksRelationView.as_view(), name='delete_relation'),
]

autodeploy/urls.py
# -*- coding: utf-8 -*-
"""autodeploy URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import django
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from autodeploy import settings
from autodeploy.apps.index.views import IndexView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', include('autodeploy.apps.index.urls')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user/', include('autodeploy.apps.user.urls')),
    url(r'^server/', include('autodeploy.apps.server.urls')),
    url(r'^playbooks/', include('autodeploy.apps.playbooks.urls')),
    url(r'^operation/', include('autodeploy.apps.operation.urls')),
    url(r'^upload/', include('autodeploy.apps.common.upload_file.urls')),
]
# 加upload访问的配置
urlpatterns += [url(r'^upload/(?P<path>.*)$', django.views.static.serve,
                    {'document_root': settings.MEDIA_ROOT})]
if not settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }),
    ]

autodeploy/apps/playbooks/models.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.db import models

from autodeploy.apps.common.managers import DefaultManager
from autodeploy.apps.common.models import BaseModel

logger = logging.getLogger(__name__)


class PlayBooks(BaseModel):
    """剧本"""
    name = models.CharField(verbose_name='剧本名字', max_length=100)
    function_name = models.CharField(verbose_name='剧本说明', max_length=100)
    # books_type = models.CharField(verbose_name='剧本类型', max_length=100)
    # system_type = models.CharField(verbose_name='系统类型', max_length=100)
    # content = models.CharField(verbose_name='描述', max_length=500)
    # path = models.CharField(verbose_name='剧本路径', max_length=1000)
    objects = DefaultManager()
    objt = models.Manager()
    
    class Meta:
        db_table = 'playbooks'
        verbose_name = '剧本管理'
        verbose_name_plural = '剧本管理列表'

    def __unicode__(self):
        return unicode(self.name)
    
class PlayBooksFile(BaseModel):
    playbooks = models.ForeignKey(PlayBooks, verbose_name='剧本管理')
    path = models.CharField(verbose_name='剧本', max_length=1000)
    content = models.CharField(verbose_name='剧本描述', max_length=500)
    version = models.CharField(verbose_name='剧本版本', max_length=200)
    upload_file=models.CharField(verbose_name="剧本所需文件",max_length=1000,null=True,blank=True)
    objects = DefaultManager()
    objt = models.Manager()

    class Meta:
        db_table = 'play_books_file'
        verbose_name = '剧本文件'
        verbose_name_plural = '剧本文件列表'

autodeploy/apps/server/models.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.db import models

from autodeploy.apps.common.managers import DefaultManager
from autodeploy.apps.common.models import BaseModel
from autodeploy.apps.playbooks.models import PlayBooks

logger = logging.getLogger(__name__)

class ServerManage(BaseModel):
    """服务器管理"""
    name=models.CharField(verbose_name="项目名",max_length=20)
    content=models.CharField(verbose_name="描述",max_length=100)
    objects = DefaultManager()
    objt = models.Manager()
    class Meta:
        db_table = 'ServerManage'
        verbose_name = '项目管理'
        verbose_name_plural = '项目管理列表'
        ordering = ['-id']
    
    def __unicode__(self):
        return unicode(self.name)

class Server(BaseModel):
    """服务器节点"""
    SERVER_CHOICES = ((0, '停止'), (1, '启动'), (2, '启动失败'), (3, '启动中'))
    server_manage=models.ForeignKey(ServerManage,verbose_name='项目管理',null=True,on_delete=models.SET_NULL)
    ip = models.CharField(verbose_name='ip地址', max_length=50)
    port = models.CharField(verbose_name='端口号', max_length=50)
    ssh_user = models.CharField(verbose_name='节点账户', max_length=30)
    ssh_password = models.CharField(verbose_name='节点密码', max_length=128)
    cpu_type = models.CharField(verbose_name='cpu类型', max_length=100, blank=True)
    cpu_total = models.CharField(verbose_name='cpu内核', max_length=50, blank=True)
    os_type = models.CharField(verbose_name='操作系统类型', max_length=50, blank=True)
    ipv4 = models.CharField(verbose_name='ipv4地址', max_length=100, blank=True)
    disk_total = models.CharField(verbose_name='硬盘总量', max_length=1000, blank=True)
    disk_mount = models.CharField(verbose_name='硬盘挂载名及容量', max_length=1000, blank=True)
    host_name = models.CharField(verbose_name='服务器主机名', max_length=100, blank=True)
    os_kernel = models.CharField(verbose_name='操作系统内核', max_length=100, blank=True)
    status = models.IntegerField(verbose_name='服务器运行状态', choices=SERVER_CHOICES, default=0)
    playbooks = models.ManyToManyField(PlayBooks, verbose_name='剧本', blank=True)
    # process = models.CharField(verbose_name='进程信息', max_length=10000, blank=True)
    objects = DefaultManager()
    objt = models.Manager()
    
    class Meta:
        db_table = 'server'
        verbose_name = '服务器'
        verbose_name_plural = '服务器列表'
        ordering = ['-id']
    
    def __unicode__(self):
        return unicode(self.id)

autodeploy/apps/server/views.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.contrib import messages
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
# from django.urls import reverse_lazy
# from django.views import View
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import View

from autodeploy.apps.common.autocomplete import AutoCompleteView
from autodeploy.apps.common.search import SearchView
from autodeploy.apps.playbooks.models import PlayBooks
from autodeploy.apps.server.forms import ServerForm, ServerManageForm
from autodeploy.apps.server.models import Server, ServerManage

logger = logging.getLogger(__name__)


class ListServerManageView(LoginRequiredMixin, SearchView):
    """项目列表"""
    template_name = 'server/manage_list.html'
    model = ServerManage
    context_object_name = 'manage_list'
    name_list = ['name']

    def get_context_data(self, **kwargs):
        context = super(ListServerManageView, self).get_context_data(**kwargs)
        # context[self.context_object_name]=
        return context


class EditorServerManageView(LoginRequiredMixin, FormView):
    """项目编辑"""
    template_name = 'server/manage_editor.html'
    form_class = ServerManageForm
    success_url = reverse_lazy('server:manage_list')
    
    def get_form_kwargs(self):
        kwargs = super(EditorServerManageView, self).get_form_kwargs()
        smid = self.kwargs.get('smid', None)  # 链接里的参数
        
        if smid:
            self.server_manage = get_object_or_404(ServerManage, pk=int(smid))
            kwargs['instance'] = self.server_manage
        else:
            self.server_manage = ServerManage()
        return kwargs
    
    # def get_queryset(self):
    #
    #     return super(ProductAddEditView, self).get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super(EditorServerManageView, self).get_context_data(**kwargs)
        # 这里可以自己加参数
        context['smid'] = self.server_manage.id
        return context
    
    def form_valid(self, form):
        self.server_manage = form.save()
        messages.info(self.request, u'编辑成功')
        self.success_url = reverse_lazy('server:manage_list')
        return super(EditorServerManageView, self).form_valid(form)


class DetailServerManageView(LoginRequiredMixin, DetailView):
    """该项目下的节点"""
    template_name = 'server/manage_detail.html'
    model = ServerManage
    context_object_name = 'server_list'
    name_list = ['ip']

    def get_context_data(self, **kwargs):
        context = super(DetailServerManageView, self).get_context_data(**kwargs)
        # context[self.context_object_name] = self.get_object().server_set.all()
        context[self.context_object_name] = self.get_server_list()
        return context

    def get_server_list(self):
        smid = self.kwargs.get('pk', '')
        if smid:
            server_list = self.get_object().server_set.filter(self.get_filter_tuple())
        else:
            server_list = []
            logger.info(u'未传出项目编号，无法搜索')
        return server_list

    def get_filter_tuple(self):
        """不需继承"""
        search_content = self.request.GET.get('searchaction', '')
        filter_info = Q()
        for name in self.name_list:
            kwargs = {
                '{}__{}'.format(name, 'icontains'): search_content
            }
            filter_info = filter_info | Q(**kwargs)
        return filter_info


class DeleteServerManageView(LoginRequiredMixin, View):
    """删除该服务器"""

    def get(self, request, *args, **kwargs):
        result = 0  # 0是删除失败
        try:
            smid = self.kwargs.get('smid', None)
            server_manage = ServerManage.objects.get(pk=smid)
            result = server_manage.update_delete()
            logger.info(u'%s删除服务器成功%s' % (request.user, smid))
        except Exception as e:
            logger.error(u'删除服务器出错,错误信息:%s' % e)
        
        return HttpResponse(result)


class ListServerView(LoginRequiredMixin, SearchView):
    """节点列表"""
    template_name = 'server/list.html'
    model = Server
    context_object_name = 'server_list'
    name_list = ['server_manage__name', 'ip']

    def get_context_data(self, **kwargs):
        context = super(ListServerView, self).get_context_data(**kwargs)
        # context[self.context_object_name]=
        return context


class EditorServerView(LoginRequiredMixin, FormView):
    """节点编辑"""
    template_name = "server/editor.html"
    form_class = ServerForm
    success_url = reverse_lazy('server:list')
    
    def get_form_kwargs(self):
        kwargs = super(EditorServerView, self).get_form_kwargs()
        sid = self.kwargs.get('sid', None)  # 链接里的参数
        
        if sid:
            self.server = get_object_or_404(Server, pk=int(sid))
            kwargs['instance'] = self.server
        else:
            self.server = Server()
        return kwargs
    
    # def get_queryset(self):
    #
    #     return super(ProductAddEditView, self).get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super(EditorServerView, self).get_context_data(**kwargs)
        # 这里可以自己加参数
        context['sid'] = self.server.id
        context['server_manage'] = self.server.server_manage
        return context
    
    def form_valid(self, form):
        self.server = form.save()
        messages.info(self.request, u'编辑成功')
        self.success_url = reverse_lazy('server:list')
        return super(EditorServerView, self).form_valid(form)


class AutoCompleteManageListView(LoginRequiredMixin, AutoCompleteView):
    """创建节点时搜索匹配项目名"""
    model = ServerManage
    name='name'

class DetailServerView(LoginRequiredMixin, DetailView):
    """服务器详情"""
    template_name = 'server/detail.html'
    model = Server
    
    def get_context_data(self, **kwargs):
        context = super(DetailServerView, self).get_context_data(**kwargs)
        context['play_books'] = self.get_object().playbooks.all()
        # context['operation_list'] = self.get_object().operationlog_set.all()
        return context


class DeleteServerView(LoginRequiredMixin, View):
    """删除服务器"""
    
    def get(self, request, *args, **kwargs):
        result = 0  # 0是删除失败
        try:
            sid = self.kwargs.get('sid', None)
            server = Server.objects.get(pk=sid)
            result = server.update_delete()
            logger.info(u'%s删除节点成功%s' % (request.user, sid))
        except Exception as e:
            logger.error(u'删除节点出错,错误信息:%s' % e)
        
        return HttpResponse(result)


class DeletePlayBooksRelationView(LoginRequiredMixin, View):
    """将剧本和服务器取关"""
    
    def post(self, request, *args, **kwargs):
        result = {'code': 0, 'msg': ''}
        server = self.get_server()
        play_book = self.get_play_book()
        if server and play_book:
            server.playbooks.remove(play_book)
            # server.save()
            logger.info('删除成功')
            result['code'] = 1
            result['msg'] = '删除成功'
        else:
            logger.error("删除失败，服务器或剧本不存在")
            result['msg'] = '删除失败，服务器或剧本不存在'
        return JsonResponse(result)
    
    def get_server(self):
        sid = self.request.POST.get('sid', '')
        try:
            server = Server.objects.get(pk=sid)
        except Exception as e:
            logger.error('不存在该服务器,错误:%s' % e)
            server = None
        return server
    
    def get_play_book(self):
        pbid = self.request.GET.get('pbid', '')
        try:
            play_book = PlayBooks.objects.get(pk=pbid)
        except Exception as e:
            logger.error('不存在该剧本,错误:%s' % e)
            play_book = None
        return play_book

autodeploy/apps/server/templates/server/editor.html
{% extends 'base/base_width_left.html' %}
{% load staticfiles %}
{% block flag %}server{% endblock %}
{% block style %}
   <link rel="stylesheet" href="{% static 'autosearch/css/styles.css' %}"/>
{% endblock %}
{% block path %}
    <a href="{% url 'server:list' %}" title="" class="tip-bottom">项目/节点管理</a>
    <a href="" title="" class="tip-bottom">节点编辑</a>
{% endblock %}
{% block container %}
    <form action="" method="POST" onsubmit="return true" class="form-horizontal" enctype="multipart/form-data"
          novalidate="novalidate">
        {% csrf_token %}
        <div class="form-group"><label class="col-sm-2 control-label" for="id_server_manage">项目管理</label>
            <div class="col-sm-4">
{#                <select name="server_manage" title="" required="" class="form-control"#}
{#                                          id="id_server_manage">#}
{#                <option value="" selected="">---------</option>#}
{##}
{#                <option value="1">啊啊啊</option>#}
{##}
{#            </select>#}
                <input hidden name="server_manage" value="{{ server_manage.id }}"/>
                <input name="" value="{{ server_manage.name }}" title="" required="" id="id_server_manage" maxlength="50"
                       placeholder="" class="form-control input-lg null" type="text">
{#                <div id="selction-ajax"></div>#}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_ip">Ip地址</label>
            <div class="col-sm-4">
{#                <input name="ip" value="192.168.1.108" title="" required="" id="id_ip" maxlength="50"#}
{#                       placeholder="请输入ip地址" class="form-control input-lg null" type="text">#}
                {{ form.ip }}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_port">端口号</label>
            <div class="col-sm-4">
{#                <input name="port" value="22" title="" required="" id="id_port" maxlength="50"#}
{#                                         placeholder="请输入ip端口" class="form-control input-lg null" type="text">#}
            {{ form.port}}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_ssh_user">节点账户</label>
            <div class="col-sm-4">
{#                <input name="ssh_user" value="root" title="" required="" id="id_ssh_user"#}
{#                                         maxlength="30" placeholder="请输入ip的账户名" class="form-control input-lg null"#}
{#                                         type="text">#}
                {{ form.ssh_user}}
            </div>
        </div>
        <div class="form-group"><label class="col-sm-2 control-label" for="id_ssh_password">节点密码</label>
            <div class="col-sm-4">
{#                <input name="ssh_password" value="111111" title="" required="" id="id_ssh_password"#}
{#                                         maxlength="128" placeholder="请输入ip的账户密码" class="form-control input-lg null"#}
{#                                         type="text">#}
            {{ form.ssh_password}}
            </div>
        </div>


        <div class="form-group">
            <button type="button" class="btn btn-primary col-xs-11 col-md-1 col-md-offset-3">保
                存
            </button>
            <!-- 				<a href="" class="btn btn-default col-xs-11 col-md-1 col-md-offset-1">返回</a> -->
        </div>


    </form>

{% endblock %}
{% block footjs %}
{#<script type="application/javascript" src="{% static 'autosearch/jquery-1.8.2.min.js' %}"></script>#}
<script type="application/javascript" src="{% static 'autosearch/js/jquery.mockjax.js' %}"></script>
<script type="application/javascript" src="{% static 'autosearch/js/jquery.autocomplete.js' %}"></script>
<script type="application/javascript" src="{% static 'autosearch/js/countries.js' %}"></script>
<script>
 $("#id_server_manage").autocomplete({
        minChars: 1,
        maxHeight:300,
        serviceUrl:'{% url 'server:autocomplete' %}',
        //lookup: countriesArray,
        //lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
         //   var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
          //  return re.test(suggestion.value);
        //},
        onSelect: function(suggestion) {
            $('input[name="server_manage"]').val(suggestion.data);
        },
{#        onHint: function (hint) {#}
{#            $('#id_server_manage').val(hint);#}
{#        },#}
        onInvalidateSelection: function() {
           $('input[name="server_manage"]').val('');
        }
 });
        $(".btn").on('click',function(){
            var smid=$('input[name="server_manage"]').val();
            if(smid != ''){
                $("form").submit();
            }else{
                var item=$("#id_server_manage").val();
                alert("项目:"+item+",不存在");
            }
        })
</script>
{% endblock %}

autodeploy/apps/server/templates/server/manage_editor.html
{% extends 'base/form_horizontal.html' %}
{% block flag %}server{% endblock %}

{% block path %}
    <a href="{% url 'server:list' %}" title="" class="tip-bottom">项目/节点管理</a>
    <a href="" title="" class="tip-bottom">项目编辑</a>
{% endblock %}
{#{% block container %}#}
{#    #}
{#{% endblock %}#}

autodeploy/apps/server/templates/server/playbooks.html
{% load pagination_tags %}
{% autopaginate play_books %}
<table class="table table-hover table-bordered ">
            <thead>
            <tr>
                <th>剧本名称</th>
                <th>剧本功能</th>
                <th>系统类型</th>
                <th>版本选择</th>
{#                <th>更新时间</th>#}
                <th>操作</th>
            </tr>
            </thead>
            {% for play_book in play_books %}
                <tr>
                    <td>{{ play_book.name }}</td>
                    <td>
                        {{ play_book.function_name }}
                    </td>
                    <td>{{ play_book.system_type }}</td>
                    <td>
                        <select class="version">
                            {% for file in play_book.playbooksfile_set.all %}
                                <option value="{{ file.id }}">{{ file.version }}</option>
                            {% endfor %}
                        </select>
                    </td>
{#                    <td>{{ play_book.update_time }}</td>#}
                    <td>
{#                        <button class="btn deletebtn btn-default btn-sm"#}
{#                                deleteurl="{% url 'coupon:create' %}">删除#}
{#                        </button>#}
                        <button class="btn btn-default btn-sm run_books"
                                url="{% url 'playbooks:run'%}?pbid={{ play_book.id }}">执行
                        </button>
                        <button class="btn btn-default btn-sm delete_relation"
                                url="{% url 'server:delete_relation'%}?pbid={{ play_book.id }}">取消关联
                        </button>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8"><p>没有查询到相关信息.</p></td>
                </tr>
            {% endfor %}
        </table>
     {% paginate %}