autodeploy/apps/playbooks/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.playbooks.views import DetailPlayBookView, ListPlayBooksView, EditorPlayBookView, PlayBooksView, \
    DeletePlayBooksView, ListBookFileView, EditorBookFileView, DeleteBookFileView, ReplayPlayBooksView, \
    VersionIsExistView

logger = logging.getLogger(__name__)
app_name = 'playbooks'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'file/list/$', ListBookFileView.as_view(), name='file_list'),
    url(r'list/$', ListPlayBooksView.as_view(), name='list'),
    url(r'file/editor/(?P<fid>\d{1,10})?/?$', EditorBookFileView.as_view(), name='file_editor'),
    url(r'editor/(?P<pbid>\d{1,10})?/?$', EditorPlayBookView.as_view(), name='editor'),
    
    url(r'detail/(?P<pk>\d{1,10})?/?$', DetailPlayBookView.as_view(), name='detail'),
    url(r'file/delete/(?P<fid>\d{1,10})?/?$', DeleteBookFileView.as_view(), name='file_delete'),
    url(r'delete/(?P<pbid>\d{1,10})?/?$', DeletePlayBooksView.as_view(), name='delete'),
    url(r'run/$', PlayBooksView.as_view(), name='run'),
    url(r'replay/$', ReplayPlayBooksView.as_view(), name='replay'),#日志重新运行剧本
    url(r'version/is_exist/$', VersionIsExistView.as_view(), name='version_is_exist'),#剧本版本是否存在

]

autodeploy/apps/server/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.server.views import ListServerView, EditorServerView, DetailServerView, DeleteServerView, \
    DeletePlayBooksRelationView, ListServerManageView, EditorServerManageView, DetailServerManageView, \
    DeleteServerManageView, AutoCompleteManageListView

logger = logging.getLogger(__name__)
app_name = 'server'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'manage/list/$', ListServerManageView.as_view(), name='manage_list'),
    url(r'manage/editor/(?P<smid>\d{1,10})?/?$', EditorServerManageView.as_view(), name='manage_editor'),
    url(r'manage/detail/(?P<pk>\d{1,10})?/?$', DetailServerManageView.as_view(), name='manage_detail'),
    url(r'manage/delete/(?P<smid>\d{1,10})?/?$', DeleteServerManageView.as_view(), name='manage_delete'),

    url(r'list/$', ListServerView.as_view(), name='list'),
    url(r'editor/(?P<sid>\d{1,10})?/?$', EditorServerView.as_view(), name='editor'),
    url(r'autocomplete/$', AutoCompleteManageListView.as_view(), name='autocomplete'),
    url(r'detail/(?P<pk>\d{1,10})/$', DetailServerView.as_view(), name='detail'),
    url(r'delete/(?P<sid>\d{1,10})/$', DeleteServerView.as_view(), name='delete'),
    url(r'delete/relation/$', DeletePlayBooksRelationView.as_view(), name='delete_relation'),
]

autodeploy/urls.py
# -*- coding: utf-8 -*-
"""autodeploy URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import django
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from autodeploy import settings
from autodeploy.apps.index.views import IndexView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', include('autodeploy.apps.index.urls')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user/', include('autodeploy.apps.user.urls')),
    url(r'^server/', include('autodeploy.apps.server.urls')),
    url(r'^playbooks/', include('autodeploy.apps.playbooks.urls')),
    url(r'^operation/', include('autodeploy.apps.operation.urls')),
    url(r'^upload/', include('autodeploy.apps.common.upload_file.urls')),
]
# 加upload访问的配置
urlpatterns += [url(r'^upload/(?P<path>.*)$', django.views.static.serve,
                    {'document_root': settings.MEDIA_ROOT})]
if not settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }),
    ]

autodeploy/apps/playbooks/models.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.db import models

from autodeploy.apps.common.managers import DefaultManager
from autodeploy.apps.common.models import BaseModel

logger = logging.getLogger(__name__)


class PlayBooks(BaseModel):
    """剧本"""
    name = models.CharField(verbose_name='剧本名字', max_length=100)
    function_name = models.CharField(verbose_name='剧本说明', max_length=100)
    # books_type = models.CharField(verbose_name='剧本类型', max_length=100)
    # system_type = models.CharField(verbose_name='系统类型', max_length=100)
    # content = models.CharField(verbose_name='描述', max_length=500)
    # path = models.CharField(verbose_name='剧本路径', max_length=1000)
    objects = DefaultManager()
    objt = models.Manager()
    
    class Meta:
        db_table = 'playbooks'
        verbose_name = '剧本管理'
        verbose_name_plural = '剧本管理列表'

    def __unicode__(self):
        return unicode(self.name)
    
class PlayBooksFile(BaseModel):
    playbooks = models.ForeignKey(PlayBooks, verbose_name='剧本管理')
    path = models.CharField(verbose_name='剧本', max_length=1000)
    content = models.CharField(verbose_name='剧本描述', max_length=500)
    version = models.CharField(verbose_name='剧本版本', max_length=200)
    upload_file=models.CharField(verbose_name="剧本所需文件",max_length=1000,null=True,blank=True)
    objects = DefaultManager()
    objt = models.Manager()

    class Meta:
        db_table = 'play_books_file'
        verbose_name = '剧本文件'
        verbose_name_plural = '剧本文件列表'

autodeploy/apps/server/models.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.db import models

from autodeploy.apps.common.managers import DefaultManager
from autodeploy.apps.common.models import BaseModel
from autodeploy.apps.playbooks.models import PlayBooks

logger = logging.getLogger(__name__)

class ServerManage(BaseModel):
    """服务器管理"""
    name=models.CharField(verbose_name="项目名",max_length=20)
    content=models.CharField(verbose_name="描述",max_length=100)
    objects = DefaultManager()
    objt = models.Manager()
    class Meta:
        db_table = 'ServerManage'
        verbose_name = '项目管理'
        verbose_name_plural = '项目管理列表'
        ordering = ['-id']
    
    def __unicode__(self):
        return unicode(self.name)

class Server(BaseModel):
    """服务器节点"""
    SERVER_CHOICES = ((0, '停止'), (1, '启动'), (2, '启动失败'), (3, '启动中'))
    server_manage=models.ForeignKey(ServerManage,verbose_name='项目管理',null=True,on_delete=models.SET_NULL)
    ip = models.CharField(verbose_name='ip地址', max_length=50)
    port = models.CharField(verbose_name='端口号', max_length=50)
    ssh_user = models.CharField(verbose_name='节点账户', max_length=30)
    ssh_password = models.CharField(verbose_name='节点密码', max_length=128)
    cpu_type = models.CharField(verbose_name='cpu类型', max_length=100, blank=True)
    cpu_total = models.CharField(verbose_name='cpu内核', max_length=50, blank=True)
    os_type = models.CharField(verbose_name='操作系统类型', max_length=50, blank=True)
    ipv4 = models.CharField(verbose_name='ipv4地址', max_length=100, blank=True)
    disk_total = models.CharField(verbose_name='硬盘总量', max_length=1000, blank=True)
    disk_mount = models.CharField(verbose_name='硬盘挂载名及容量', max_length=1000, blank=True)
    host_name = models.CharField(verbose_name='服务器主机名', max_length=100, blank=True)
    os_kernel = models.CharField(verbose_name='操作系统内核', max_length=100, blank=True)
    status = models.IntegerField(verbose_name='服务器运行状态', choices=SERVER_CHOICES, default=0)
    playbooks = models.ManyToManyField(PlayBooks, verbose_name='剧本', blank=True)
    # process = models.CharField(verbose_name='进程信息', max_length=10000, blank=True)
    objects = DefaultManager()
    objt = models.Manager()
    
    class Meta:
        db_table = 'server'
        verbose_name = '服务器'
        verbose_name_plural = '服务器列表'
        ordering = ['-id']
    
    def __unicode__(self):
        return unicode(self.id)

autodeploy/apps/playbooks/forms.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-27 上午10:33.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django import forms
from django.forms import TextInput, Textarea

from autodeploy.apps.playbooks.models import PlayBooks, PlayBooksFile

logger = logging.getLogger(__name__)


class PlayBooksForm(forms.ModelForm):
    class Meta:
        model = PlayBooks
        fields = ('name', 'function_name',   )
        widgets = {
            'name': TextInput(attrs={'type': 'text', 'required': 'required',
                                     'class': 'form-control input-lg null',
                                     'placeholder': '请输入剧本名字'}),
            'function_name': Textarea(attrs={'type': 'text', 'required': 'required',
                                              'class': 'form-control input-lg null',
                                              'placeholder': '剧本描述'}),
            # 'books_type': TextInput(attrs={'type': 'text', 'required': 'required',
            #                                'class': 'form-control input-lg null',
            #                                'placeholder': '剧本类型'}),
            # 'system_type': TextInput(attrs={'type': 'text', 'required': 'required',
            #                                 'class': 'form-control input-lg null',
            #                                 'placeholder': '操作系统'}),
            # 'content': Textarea(attrs={'type': 'text', 'required': 'required',
            #                            'class': 'form-control input-lg null',
            #                            'placeholder': '剧本描述'}),
            # 'path': TextInput(attrs={'type': 'text',
            #                          'readOnly': 'readOnly',
            #                          'class': 'upload_file', 'upimginfo': 'image,0,0'}),
        }
        
class PlayBooksFileForm(forms.ModelForm):
    class Meta:
        model = PlayBooksFile
        fields = ('playbooks', 'content','version','path','upload_file')
        widgets = {
            # 'playbooks': Select(attrs={'required': 'required',
            #                          'class': 'form-control input-lg null',
            #                          }),
            'version': TextInput(attrs={'type': 'text', 'required': 'required',
                                              'class': 'form-control input-lg null',
                                              'placeholder': '版本'}),
            'content': Textarea(attrs={'type': 'text', 'required': 'required',
                                       'class': 'form-control input-lg null',
                                       'placeholder': '版本描述'}),
            'path': TextInput(attrs={'type': 'text',
                                     'readOnly': 'readOnly',
                                     'class': 'form-control input-lg null upload_file', 'upimginfo': 'image,0,0'}),
            'upload_file': TextInput(attrs={'type': 'text',
                                     'readOnly': 'readOnly',
                                     'class': 'form-control input-lg null upload_zip', 'upimginfo': 'image,0,0'}),
        }

autodeploy/apps/playbooks/templates/playbooks/editor.html
{% extends 'base/form_horizontal.html' %}
{% block flag %}playbooks{% endblock %}
{% block path %}
    <a href="{% url 'playbooks:list' %}" title="" class="tip-bottom"> 剧本管理</a>
    <a href="" title="" class="tip-bottom"> 管理编辑</a>
{% endblock %}
{% block headcontent %}
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="">管理编辑</a></li>
        {% if pbid %}
        <li role="presentation"><a href="{% url 'playbooks:file_list'%}?pbid={{ pbid }}">版本列表</a></li>
        <li role="presentation"><a href="{% url 'playbooks:detail' pk=pbid%}">剧本运行</a></li>
        {% endif %}

    </ul>
{% endblock %}
{% block footjs %}
    <script type="text/javascript" src="/static/uploadify/jquery.uploadify.min.js"></script>
    <script type="text/javascript" src="/static/uploadify/uploadify_file.js"></script>
{#    <script type="text/javascript" src="/static/uploadify/uploadimg.js"></script>#}
{% endblock %}
{#<div class="col-sm-4">#}
{#    <input type="text" name="path" value="/home/hcx/workspace/autodeploy/autodeploy/uplod/task/information" title="" upimginfo="image,0,0" required="" id="id_path" readonly="readOnly" maxlength="1000" placeholder="剧本路径" class="form-control imginput">#}
{#    <div style="display:inline;"><a class="btn btn-default" onclick="upload_iframe(this,'image',0,0)">#}
{#        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>#}
{#        上传图片</a>&nbsp;<a class="btn btn-default" onclick="delete_img(this)">清除图片</a>#}
{#        <span name="" class="upimg">/home/hcx/workspace/autodeploy/autodeploy/uplod/task/information</span>#}
{#    </div>#}
{#    <div class="preview_img"><br>#}
{#        <img width="100px" src="/home/hcx/workspace/autodeploy/autodeploy/uplod/task/information?2014">#}
{#    </div>#}
{#</div>#}

autodeploy/apps/playbooks/templates/playbooks/file_list.html
{% extends "base/base_width_left.html" %}
{% load pagination_tags %}

{% block flag %}playbooks{% endblock %}

{% block path %}
    <a href="" title="" class="tip-bottom"> 剧本管理</a>
    <a href="" title="" class="tip-bottom"> 版本列表</a>
{% endblock %}
{#{% block searchname %}searchaction{% endblock %}#}
{#{% block searchtip %}订单编号{% endblock %}#}

{% block container %}
    {{ block.super }}
        {% autopaginate file_list %}
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="{% url 'playbooks:editor' pbid=pbid%}">管理编辑</a></li>
            <li role="presentation" class="active"><a href="{#% url 'product:theme_list' %#}">版本列表</a></li>
            <li role="presentation"><a href="{% url 'playbooks:detail' pk=pbid%}">剧本运行</a></li>
        </ul>
    <div hidediv="hide" class="center-block">
        <div class="dropdown" style="display:inline">
{#                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"#}
            {#                                aria-expanded="true">#}
            {#                            按分类查看#}
            {#                            <span class="caret"></span>#}            {#                        </button>#}
            <a class="btn btn-default dropdown-toggle" type="button" href="{% url 'playbooks:file_editor' %}?pbid={{ pbid }}">
                           创建
            </a>
            {#            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">#}
            {#                <li role="presentation">#}
            {#                    <a role="menuitem" tabindex="-1" href="{% url 'order:order_list' %}">全部</a>#}
            {#                </li>#}
            {#                {% for status in status_tuple %}#}
            {#                    <li role="presentation">#}
            {#                        <a role="menuitem" tabindex="-1"#}
            {#                           href="{% url 'order:order_list' %}?status={{ status.0 }}">{{ status.1 }}</a>#}
            {#                    </li>#}
            {#                {% endfor %}#}
            {#            </ul>#}
        </div>
        {#        <a href="{% url 'product:product_form' %}" class="btn btn-primary">添 加</a>#}
         <form method="get">
             <input hidden class="input-sm" name="pbid" value="{{pbid }}" placeholder="输入版本搜索"/>
            <input class="input-sm" name="searchaction" placeholder="输入版本搜索"/>
            <button class="btn btn-default">搜索</button>
        {#        <a href="{% url 'product:product_form' %}" class="btn btn-primary">添 加</a>#}
        </form>
    </div>
    <div hidediv="hide" class="table-responsive">
        <table class="table table-hover table-bordered ">
            <thead>
            <tr>
                <th>剧本版本</th>
                <th>剧本描述</th>
                <th>文件夹</th>
                <th>上传时间</th>
                <th>操作</th>
            </tr>
            </thead>
            {% for file in file_list %}
                <tr>
                    <td>{{ file.version }}</td>
                    <td>
                        {{ file.content }}
                    </td>
                    <td>/home/item/workspace/autodeploy/autodeploy/upload/{{ file.playbooks.id }}_{{ file.version }}</td>
                    <td>{{ file.create_time }}</td>
{#                    <td>{{ play_book.system_type }}</td>#}
{#                    <td>{{ play_book.path }}</td>#}
{#                    <td>{{ play_book.update_time }}</td>#}
                    <td>
                        <button class="btn deletebtn btn-default btn-sm"
                                deleteurl="{% url 'playbooks:file_delete' fid=file.id %}">删除
                        </button>
                        <a class="btn btn-default btn-sm"
                                href="{% url 'playbooks:file_editor' fid=file.id%}">编辑
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8"><p>没有查询到相关信息.</p></td>
                </tr>
            {% endfor %}
        </table>
     {% paginate %}
{#        <div class="pagination">#}
{#            <span class="step-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.prevous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{#                <span class="current">#}
{#                    page {{ page_obj.number }} of {{ paginator.num_pages }}.#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{##}
{#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}

    </div>
{% endblock %}
{% block footjs %}
    <script>
        $('.change_status').click("on", function () {
            var url = $(this).attr('change_url');
            $(this).attr('disabled', 'disabled');
            var yes = function () {
                //退款需要时间，显示加载的提示
                layer.load(2, {time: 10 * 1000});
                $.get(url, {}, function (data) {
                    if (data.url) {
                        window.open(data.url);
                    } else if (data.code == 1) {
                        showMsg(options = {msg: "修改成功"});
                        location.reload();
                    } else {
                        location.reload();
                    }

                })
            };
            showYesorNo("是否修改订单状态", yes);

        });
        $('.shipments').on('click', function () {
            var url = $(this).attr('change_url');
            var options = {
                title: "增加物流",
                area: ['300', '400'],
                content: [url, 'no'],
                yes: function (index) {
                    var logistics_form = layer.getChildFrame("form", index);
                    if (logistics_form.find('#id_logistics_id').val() == '' || logistics_form.find('#id_logistics_company').val() == '') {
                        showMsg(options = {msg: "物流单号或物流公司未填", icon: 5});
                    } else {
                        $.post(url, logistics_form.serialize(), function (data) {
                            if (data == 1) {
                                location.reload();
                            } else if (data == 0) {
                                showMsg(options = {msg: "修改失败", icon: 5});
                            } else {
                                location.href = data;
                            }
                            ;
                        });

                    }
                },
            }
            showIframe(options)
        });

    </script>
{% endblock %}

autodeploy/apps/playbooks/templates/playbooks/running.html
{% extends "base/base_width_left.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block style %}
   <link rel="stylesheet" href="{% static 'autosearch/css/styles.css' %}"/>
{% endblock %}
{% block flag %}playbooks{% endblock %}
{% block path %}
    <a href="" title="" class="tip-bottom"> 剧本管理</a>
{% endblock %}

{#{% block searchname %}searchaction{% endblock %}#}
{#{% block searchtip %}订单编号{% endblock %}#}

{% block container %}
    {{ block.super }}
    {% autopaginate server_list %}
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'playbooks:editor' pbid=play_book.id %}">管理编辑</a></li>
        <li role="presentation"><a href="{% url 'playbooks:file_list' %}?pbid={{ play_book.id }}">版本列表</a></li>
        <li role="presentation" class="active"><a href="{#% url 'product:theme_list' %#}">剧本运行</a></li>
    </ul>
    <div hidediv="hide" class="center-block">
        <div class="panel panel-default">
            <div class="panel-heading"><span><h4>{{ play_book.name }}</h4></span></div>
            <ul class="list-group">
                <li class="list-group-item"><span>剧本名称:</span><span
                        style="padding-left: 35%;text-align: center">{{ play_book.name }}</span></li>
                <li class="list-group-item"><span>功能类型:</span><span
                        style="padding-left: 35%;text-align: center">{{ play_book.function_name }}</span></li>
                {#                    <li class="list-group-item"><span>剧本类型:</span><span style="padding-left: 35%;text-align: center">{{ play_book.books_type }}</span></li>#}
                {#                    <li class="list-group-item"><span>剧本路径:</span><span style="padding-left: 35%;text-align: center">{{ play_book.path }}</span></li>#}
                <li class="list-group-item"><span>系统类型:</span><span
                        style="padding-left: 35%;text-align: center">{{ play_book.system_type }}</span></li>
                {#                    <li class="list-group-item"><span>剧本描述:</span><span style="padding-left: 35%;text-align: center">{{ play_book.content }}</span></li>#}
                <li class="list-group-item">
                    <span>请选择剧本版本：</span>
                    <select name="fid" class="version ">
                        {% for file in play_book.playbooksfile_set.all %}
                            <option value="{{ file.id }}">{{ file.version }}</option>
                        {% endfor %}
                    </select>
                    <button type="button" class="btn btn-default run" style="margin: 5px 5px"
                            url="{% url 'playbooks:run' %}?pbid={{ play_book.id }}">运行剧本
                    </button>
                    <form method="get" class="" style="width: 40%;float: right;margin-right: 22%">
                        <span>请选择项目</span>
                        <input hidden name="manage"/>
                        <input class="input-sm" name="" id="id_server_manage"placeholder="输入项目"/>
{#                        <select name="manage" style="width: 10%;height: 25px">#}
{#                            <option value="">所有</option>#}
{#                            {% for manage in manage_list %}#}
{#                            <option value="{{ manage.id }}">{{ manage.name }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
                        <input class="input-sm" name="searchaction" placeholder="输入节点ip搜索"/>
                        <button class="btn btn-default">搜索
                        </button>
                    </form>
                    <div style="clear: both"></div>
                </li>
            </ul>

            {#            <button type="button" class="btn btn-default run" style="margin: 5px 5px" url="{% url 'playbooks:run' %}?pbid={{ play_book.id }}">运行剧本</button>#}
        </div>
    </div>
    <form method="post" class="run_form">
        {% csrf_token %}
        <div hidediv="hide" class="table-responsive">
            <table class="table table-hover table-bordered ">
                <thead>
                <tr>
                    <th><input type="checkbox" class="all"></th>
                    <th>节点ip</th>
                    <th>节点端口</th>
                    <th>节点帐号</th>
                    <th>节点密码</th>
{#                    <th>服务器状态</th>#}
                    {#                <th>操作</th>#}
                    {#                <th>剧本路径</th>#}
                    {#                <th>更新时间</th>#}
                    <th>操作</th>
                </tr>
                </thead>
                {% for server in server_list %}
                    <tr>
                        <td>
                            <input type="checkbox" value="{{ server.id }}" name="sid"
                                   {% if server in play_book.server_set.all %}checked{% endif %}/>
                        </td>
                        <td>{{ server.ip }}</td>
                        <td>
                            {{ server.port }}
                        </td>
                        <td>{{ server.ssh_user }}</td>
                        <td>
{#                            {{ server.ssh_password }}#}
                            ******
                        </td>
{#                        <td>{{ server.get_status_display }}</td>#}
                        <td>
                            <a class="btn btn-default btn-sm"
                               href="{% url 'server:editor' sid=server.id %}">编辑
                            </a>
                            <a class="btn btn-default btn-sm"
                               href="{% url 'server:detail' pk=server.id %}">详情
                            </a>
{#                            <a class="btn btn-default btn-sm run"#}
{#                               url="{% url 'playbooks:run' %}">更新#}
{#                            </a>#}
                            <button class="btn deletebtn btn-default btn-sm"
                                    deleteurl="{% url 'server:delete' sid=server.id %} ">删除
                            </button>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="8"><p>没有查询到相关信息.</p></td>
                    </tr>
                {% endfor %}
            </table>
            {% paginate %}
            {#        <div class="pagination">#}
            {#            <span class="step-links">#}
            {#                {% if page_obj.has_previous %}#}
            {#                    <a href="?page={{ page_obj.prevous_page_number }}">上一页</a>#}
            {#                {% endif %}#}
            {#                <span class="current">#}
            {#                    page {{ page_obj.number }} of {{ paginator.num_pages }}.#}
            {#                </span>#}
            {#                {% if page_obj.has_next %}#}
            {##}
            {#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
            {#                {% endif %}#}
            {#            </span>#}
            {#        </div>#}

        </div>
    </form>
{% endblock %}
{% block footjs %}
    <script type="application/javascript" src="{% static 'autosearch/js/jquery.mockjax.js' %}"></script>
<script type="application/javascript" src="{% static 'autosearch/js/jquery.autocomplete.js' %}"></script>
<script type="application/javascript" src="{% static 'autosearch/js/countries.js' %}"></script>
    <script>
        $('.all').on('click', function () {
            if ($(this).is(':checked')) {
                $('td').find('input[name="sid"]').prop('checked', true);
                {#                alert($('td').find('input[name="sid"]').attr('checked'))#}
            } else {
                $('td').find('input[name="sid"]').removeAttr('checked');
            }
        });
        $('.run').on('click', function () {
            var $form = $('.run_form');
            var $fid = $('.version').val();
            if (!$fid) {
                alert('请选择剧本版本')
            } else {
                if(is_server()){
                    var url = $(this).attr('url');
                    var url_all=url+'&fid='+$fid;
                    $.post(url_all, $form.serialize(), function (data) {
                        if (data == 1) {
                            alert('剧本已运行');
                            time_lazy();
                        } else {
                            alert('运行失败');
                        }
                    })
                }else{
                    alert('请选择一个服务器！');
                }
            }
        });
        function is_server(){
            var $sid_list=$("input[name='sid']");
            for(var i=0;i<$sid_list.length;i++){
                if($sid_list.eq(i).is(':checked')){
                    return true
                }
            }
            return false
        }
        //搜索匹配
     $("#id_server_manage").autocomplete({
        minChars: 1,
        maxHeight:300,
        serviceUrl:'{% url 'server:autocomplete' %}',
        //lookup: countriesArray,
        //lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
         //   var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
          //  return re.test(suggestion.value);
        //},
        onSelect: function(suggestion) {
            $('input[name="manage"]').val(suggestion.data);
        },
{#        onHint: function (hint) {#}
{#            $('#id_server_manage').val(hint);#}
{#        },#}
        onInvalidateSelection: function() {
           $('input[name="_manage"]').val('');
        }
 });
    </script>
{% endblock %}