autodeploy/apps/index/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 上午11:12.
@author: 胡超翔
"""
from django.conf.urls import url

from autodeploy.apps.index.views import IndexView

app_name = 'index'
urlpatterns = [
    url(r'$', IndexView.as_view(), name='index'),
]

autodeploy/apps/operation/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps import operation
from autodeploy.apps.operation import views
from autodeploy.apps.operation.views import ListOperationView, DeleteOperationView, DetailOperationView, \
    get_operation_list

logger = logging.getLogger(__name__)
app_name = 'operation'
urlpatterns = [
    url(r'detail/(?P<pk>\d{1,10})/$', DetailOperationView.as_view(), name='detail'),
    url(r'list/$', ListOperationView.as_view(), name='list'),
    url(r'websocket/$',get_operation_list,name='sm_list'),
    url(r'delete/(?P<oid>\d{1,10})/$', DeleteOperationView.as_view(), name='delete'),
]

autodeploy/apps/playbooks/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-20 下午2:36.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.playbooks.views import DetailPlayBookView, ListPlayBooksView, EditorPlayBookView, PlayBooksView, \
    DeletePlayBooksView, ListBookFileView, EditorBookFileView, DeleteBookFileView, ReplayPlayBooksView, \
    VersionIsExistView

logger = logging.getLogger(__name__)
app_name = 'playbooks'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'file/list/$', ListBookFileView.as_view(), name='file_list'),
    url(r'list/$', ListPlayBooksView.as_view(), name='list'),
    url(r'file/editor/(?P<fid>\d{1,10})?/?$', EditorBookFileView.as_view(), name='file_editor'),
    url(r'editor/(?P<pbid>\d{1,10})?/?$', EditorPlayBookView.as_view(), name='editor'),
    
    url(r'detail/(?P<pk>\d{1,10})?/?$', DetailPlayBookView.as_view(), name='detail'),
    url(r'file/delete/(?P<fid>\d{1,10})?/?$', DeleteBookFileView.as_view(), name='file_delete'),
    url(r'delete/(?P<pbid>\d{1,10})?/?$', DeletePlayBooksView.as_view(), name='delete'),
    url(r'run/$', PlayBooksView.as_view(), name='run'),
    url(r'replay/$', ReplayPlayBooksView.as_view(), name='replay'),#日志重新运行剧本
    url(r'version/is_exist/$', VersionIsExistView.as_view(), name='version_is_exist'),#剧本版本是否存在

]

autodeploy/apps/server/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.conf.urls import url

from autodeploy.apps.server.views import ListServerView, EditorServerView, DetailServerView, DeleteServerView, \
    DeletePlayBooksRelationView, ListServerManageView, EditorServerManageView, DetailServerManageView, \
    DeleteServerManageView, AutoCompleteManageListView

logger = logging.getLogger(__name__)
app_name = 'server'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'manage/list/$', ListServerManageView.as_view(), name='manage_list'),
    url(r'manage/editor/(?P<smid>\d{1,10})?/?$', EditorServerManageView.as_view(), name='manage_editor'),
    url(r'manage/detail/(?P<pk>\d{1,10})?/?$', DetailServerManageView.as_view(), name='manage_detail'),
    url(r'manage/delete/(?P<smid>\d{1,10})?/?$', DeleteServerManageView.as_view(), name='manage_delete'),

    url(r'list/$', ListServerView.as_view(), name='list'),
    url(r'editor/(?P<sid>\d{1,10})?/?$', EditorServerView.as_view(), name='editor'),
    url(r'autocomplete/$', AutoCompleteManageListView.as_view(), name='autocomplete'),
    url(r'detail/(?P<pk>\d{1,10})/$', DetailServerView.as_view(), name='detail'),
    url(r'delete/(?P<sid>\d{1,10})/$', DeleteServerView.as_view(), name='delete'),
    url(r'delete/relation/$', DeletePlayBooksRelationView.as_view(), name='delete_relation'),
]

autodeploy/apps/user/urls.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import url

from autodeploy.apps.user.views import LoginView, LogoutView

app_name = 'user'
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('autodeploy.apps.index.urls')),url(r'', include('autodeploy.apps.index.urls')),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
]

autodeploy/urls.py
# -*- coding: utf-8 -*-
"""autodeploy URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import django
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from autodeploy import settings
from autodeploy.apps.index.views import IndexView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', include('autodeploy.apps.index.urls')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user/', include('autodeploy.apps.user.urls')),
    url(r'^server/', include('autodeploy.apps.server.urls')),
    url(r'^playbooks/', include('autodeploy.apps.playbooks.urls')),
    url(r'^operation/', include('autodeploy.apps.operation.urls')),
    url(r'^upload/', include('autodeploy.apps.common.upload_file.urls')),
]
# 加upload访问的配置
urlpatterns += [url(r'^upload/(?P<path>.*)$', django.views.static.serve,
                    {'document_root': settings.MEDIA_ROOT})]
if not settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }),
    ]

autodeploy/apps/operation/forms.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-21 下午2:42.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

logger = logging.getLogger(__name__)

autodeploy/apps/server/forms.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django import forms
from django.forms import TextInput, Textarea

from autodeploy.apps.server.models import Server, ServerManage

logger = logging.getLogger(__name__)
class ServerManageForm(forms.ModelForm):
    class Meta:
        model=ServerManage
        fields=('name','content')
        widgets={
            'name': TextInput(attrs={'type': 'text', 'required': 'required',
                                   'class': 'form-control input-lg null',
                                   'placeholder': u'请输入项目名字'}),
            'content': Textarea(attrs={'type': 'text', 'required': 'required',
                                     'class': 'form-control input-lg null',
                                     'placeholder': u'请输入对该项目的描述'}),
        }

class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = ('server_manage','ip', 'port', 'ssh_user', 'ssh_password')
        widgets = {
            'server_manage':TextInput(attrs={}),
            'ip': TextInput(attrs={'type': 'text', 'required': 'required',
                                   'class': 'form-control input-lg null',
                                   'placeholder': u'请输入ip地址'}),
            'port': TextInput(attrs={'type': 'text', 'required': 'required',
                                     'class': 'form-control input-lg null','value':'22',
                                     'placeholder': u'请输入ip端口'}),
            'ssh_user': TextInput(attrs={'type': 'text', 'required': 'required',
                                         'class': 'form-control input-lg null',
                                         'placeholder': u'请输入ip的账户名'}),
            'ssh_password': TextInput(attrs={'type': 'text', 'required': 'required',
                                             'class': 'form-control input-lg null',
                                             'placeholder': u'请输入ip的账户密码'}),
        }

autodeploy/apps/index/views.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 上午11:11.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.base import View

logger = logging.getLogger(__name__)


class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index/index.html', locals())

autodeploy/apps/operation/views.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-24 上午9:43.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.models import model_to_dict
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import DetailView
from django.views.generic import View

from autodeploy.apps.common.search import SearchView
from autodeploy.apps.operation.models import OperationLog, OperationDetail
from autodeploy.apps.server.models import Server

logger = logging.getLogger(__name__)


def create_log(operation_log, result, detail_status,status=None):
    if status == 'defeat':
        operation_log.status = status
        operation_log.save()
    try:
        OperationDetail.objects.create(operation_log=operation_log,
                                       result=result,status=detail_status)
    except Exception as e:
        logger.error('运行错误:%s' % e)
        return False
    return True


class ListOperationView(LoginRequiredMixin, SearchView):
    """获取日志列表"""
    template_name = 'operation/list.html'
    model = OperationLog
    context_object_name = 'operation_list'
    name_list = ['version', 'server_ip', 'books_name']
    
    def get_context_data(self, **kwargs):
        context = super(ListOperationView, self).get_context_data(**kwargs)
        server = self.get_server()
        status_tuple = OperationLog.RESULT_STATUS
        status = self.request.GET.get('status', '')
        self.status_show = '全部'
        queryset = self.search()
        if status:
            for t in status_tuple:
                if t[0] == status:
                    self.status_show = t[1]
        if server:
            context[self.context_object_name] = queryset.filter(server=server)
            context['server'] = server
        else:
            context['server'] = None
            context[self.context_object_name] = queryset
        context['status_show'] = self.status_show
        context['status_tuple'] = status_tuple
        context['status'] = status
        return context
    
    def get_server(self):
        sid = self.request.GET.get('sid')
        try:
            server = Server.objects.get(pk=sid)
        except Exception as e:
            logger.error('不存在该服务器,错误:%s' % e)
            server = None
        return server


class DetailOperationView(LoginRequiredMixin, DetailView):
    """日志详情"""
    template_name = 'operation/detail.html'
    model = OperationLog
    context_object_name = 'detail_list'
    
    def get_context_data(self, **kwargs):
        context = super(DetailOperationView, self).get_context_data(**kwargs)
        context[self.context_object_name] = self.get_object().operationdetail_set.filter()
        context['operation_log'] = self.get_object()
        return context


class DeleteOperationView(LoginRequiredMixin, View):
    """删除日志"""
    
    def get(self, request, *args, **kwargs):
        result = 0  # 0是删除失败
        try:
            oid = self.kwargs.get('oid', None)
            operation = OperationLog.objects.get(pk=oid)
            result = operation.update_delete()
            logger.info(u'%s删除日志成功%s' % (request.user, oid))
        except Exception as e:
            logger.error(u'删除日志出错,错误信息:%s' % e)
        
        return HttpResponse(result)


# @require_websocket
def get_operation_list(request):
    result = {'code': 0, 'operation_list': []}
    operation_list = OperationLog.objects.filter()[:10]
    for operation in operation_list:
        operation_dir = model_to_dict(operation)
        if operation_dir['end_time']:
            operation_dir['end_time'] = operation_dir['end_time'].strftime('%Y-%m-%d %H:%M:%S')
        else:
            operation_dir['end_time'] = ''
        operation_dir['create_time'] = operation.create_time.strftime('%Y-%m-%d %H:%M:%S')
        if operation.books_name:
            operation_dir['play_book_name'] = operation.books_name
        else:
            operation_dir['play_book_name'] = '更新'
            operation_dir['play_books'] = '更新'
        result['operation_list'].append(operation_dir)
    result['operation_list'].reverse()
    result['code'] = 1
    # result = json.dumps(result)
    # if request.is_websocket():
    #     request.websocket.send(result)
        # import uwsgi
        # uwsgi.websocket_handshake()
        # # import uwsgi
        # uwsgi.websocket_send(result)
    # else:
    return JsonResponse(result)
# def application(env, start_response):
#     # complete the handshake
#     uwsgi.websocket_handshake(env['HTTP_SEC_WEBSOCKET_KEY'], env.get('HTTP_ORIGIN', ''))
#     while True:
#         msg = uwsgi.websocket_recv()
#         uwsgi.websocket_send(msg)

autodeploy/apps/user/views.py
# -*- coding: utf-8 -*- 
"""
Created by hcx on 17-7-19 下午2:38.
@author: 胡超翔
"""
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic import RedirectView

from autodeploy.apps.user.forms import LoginForm

logger = logging.getLogger(__name__)


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'user/login.html'
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, locals())
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # 获取用户名,密码
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # 验证登录
            user = validate_login(request, username, password)
            if user.id:
                return redirect(request.GET.get('next', reverse('index:index')))
            else:
                messages.error(request, u'用户名或密码错误')
        else:
            messages.error(request, u'数据验证失败')
        
        return render(request, self.template_name, locals())


class LogoutView(LoginRequiredMixin, RedirectView):
    """后台登出"""
    permanent = False
    query_string = True  # 是否将GET 的查询字符串一起传递给新的地址
    pattern_name = 'user:login'  # 重定向的目标URL 模式的名称
    
    def get_redirect_url(self, *args, **kwargs):
        # 用户注销
        logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)


def validate_login(request, username, password):
    """验证用户登录"""
    # 验证用户名密码，并返回一个 user对象
    user = authenticate(username=username, password=password)
    if user:
        # 保持登录用户和后端的连接
        login(request, user)
        # 记录该用户登录成功的日志
        logger.info('%s登录成功' % username)
    else:
        # 用户提示：用户名或密码错误
        user = User()
    return user


class ResetPasswordView(LoginRequiredMixin, FormView):
    """后台密码修改"""
    template_name = 'user/reset_password.html'
    form_class = SetPasswordForm
    success_url = reverse_lazy('user:login')
    
    def get_form_kwargs(self):
        kwargs = super(ResetPasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        user = form.save()
        messages.info(self.request, u'密码修改成功')
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, user)
        return super(ResetPasswordView, self).form_valid(form)

autodeploy/templates/base/base_alert.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    {# Load the tag library #}
    {% load bootstrap3 %}
    {# Load CSS and JavaScript #}
{#    {% bootstrap_css %}#}
{#    {% bootstrap_javascript %}#}
    <title>报名系统</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- content的取值为webkit,ie-comp,ie-stand之一，区分大小写，分别代表用webkit内核，IE标准内核，IE兼容内核。  -->
    <meta name="renderer" content="webkit|ie-stand|ie-comp">

    <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'layer/skin/layer.css' %}"/>
    <!-- <link rel="stylesheet" href="{% static 'layer/skin/seaning/style.css' %}" /> -->
    <link rel="stylesheet" href="{% static 'layer/skin/layer.ext.css' %}"/>
    <!-- <link rel="stylesheet" href="css/fullcalendar.css" /> -->
    <link rel="stylesheet" href="{% static 'css/black/matrix-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/black/matrix-media.css' %}"/>

{#    <script src="http://v3.bootcss.com/assets/js/ie-emulation-modes-warning.js"></script>#}
 <script src="{% static 'js/jquery-1.9.1.min.js' %}" type="application/javascript"></script>
    <script src="{% static 'bootstrap3/js/bootsrap.min.js' %}"></script>
    <script src="{% static 'bootstrap3/js/ie-emulation-modes-warning.js' %}"></script>
    <!--[if lt IE 9]><script src="../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

    <!-- <link rel="stylesheet" href="css/jquery.gritter.css" /> -->
    <style>
        /*   .btn{margin-top:2%;margin-bottom:2%;} */
    </style>
    {% block style %}{% endblock %}
    {% block headjs %}{% endblock %}

</head>
<body style="background:none;">
<div class="container-fluid" style="margin-top:20px;">
    {% block container %}{% endblock %}
</div>
<!-- <script src="js/excanvas.min.js"></script>    -->
<!-- <script src="js/jquery.min.js"></script>  -->
<!-- <script src="js/jquery.ui.custom.js"></script> 
<script src="js/bootstrap.min.js"></script> 
<script src="js/jquery.flot.min.js"></script> 
<script src="js/jquery.flot.resize.min.js"></script> 
<script src="js/jquery.peity.min.js"></script>
<script src="js/fullcalendar.min.js"></script> -->
<!-- <script src="http://cdn.bootcss.com/typeahead.js/0.10.4/typeahead.jquery.js"></script> -->
<!-- <script src="{% static 'js/matrix.js' %}"></script>  -->
<!-- <script src="js/matrix.dashboard.js"></script> 
<script src="js/jquery.gritter.min.js"></script> 
<script src="js/matrix.interface.js"></script> 
<script src="js/matrix.chat.js"></script> 
<script src="js/jquery.validate.js"></script> 
<script src="js/matrix.form_validation.js"></script> 
<script src="js/jquery.wizard.js"></script> 
<script src="js/jquery.uniform.js"></script> 
<script src="js/select2.min.js"></script> 
<script src="js/matrix.popover.js"></script> 
<script src="js/jquery.dataTables.min.js"></script> 
<script src="js/matrix.tables.js"></script>  -->
<!-- 使IE9及以下版本支持placeholder属性 -->
{#<script src="http://cdn.bootcss.com/placeholders/3.0.2/placeholders.min.js"></script>#}
<script src="{% static 'bootstrap3/js/placeholders.min.js' %}"></script>
<script src="{% static 'js/bootstrap3-validation.js' %}"></script>

<!-- 另一个表单验证插件 -->
<!-- <script src="{% static 'js/jquery.validator.js' %}"></script> -->
<!-- <script src="{% static 'js/zh_CN.js' %}"></script> -->

<!-- 弹出框插件 -->
<script src="{% static 'layer/layer.min.js' %}" type="text/javascript"></script>
<script src="{% static 'layer/layer.js' %}" type="text/javascript"></script>
<script src="{% static 'layer/extend/layer.ext.js' %}" type="text/javascript"></script>

<script src="{% static 'js/common.js' %}" type="text/javascript"></script>
<script src="{% static 'js/pop-up-box.js' %}" type="text/javascript"></script>
<script>
    $("form").validation();
    $("button[type='submit']").on('click', function (event) {
        // 2.最后要调用 valid()方法。
        if ($("form").valid(this, "表单有误") == false) {
            //$("#error-text").text("error!"); 1.0.4版本已将提示直接内置掉，简化前端。
            return false;
        }
    });
</script>
{% block footjs %}{% endblock %}
</body>
</html>

autodeploy/templates/base/base_width_left.html
{% extends "base/base_width_top.html" %}
{% load bootstrap3 %}

{% block main %}
    {% block sidebar %}

        {% include 'base/business/left.html' %}

    {% endblock %}
    <!--main-container-part-->
    <div id="content">
        <!--breadcrumbs-->
        <div id="content-header">
            <div id="breadcrumb"><a href="{% url 'index' %}" title="" class="tip-bottom"><span
                    class="glyphicon glyphicon-home"></span> 首页</a>{% block path %}{% endblock %}</div>
        </div>
        <!--End-breadcrumbs-->
        <div class="container-fluid">
            <!--   <hr> -->
            <!--       <div class="row-fluid"> -->
            <div class="clearfix"  style="margin-top: 40px">
                {% bootstrap_messages %}
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!--end-main-container-part-->
{% endblock %}

autodeploy/templates/base/base_width_top.html
{% extends "base/base.html" %}
{% load bootstrap3 %}
{% block logo %}
    <!--Header-part-->
    <div id="header">
        <div style="float: left;width: 73px;padding-top: 30px;" class="">
            <a title="" href="{% url 'user:logout' %}"style="padding-left: 10px">
                <span class="glyphicon glyphicon-share-alt" style="color:white"></span>
                <span class="text" style="font-size: 15px;color:white">退出</span>
            </a>
        </div>
        <div style="clear: both;"></div>
        {#        <img src="" width="10%" onclick="location.href=''"/>#}
        {#        <!--   <h1 style="margin-top:0"><a href="" title="wiicome">1</a></h1> -->#}
        {#        <!--   <div style="display:block;width:210px;height:75px;padding-left:60px;paddding-top:10px;"><a href="" style="font-size:38px;">微&nbsp;&nbsp;来</a></div> -->#}
    </div>
{% endblock %}
<!--close-Header-part-->
{% block header_menu %}
    {% include 'base/business/top.html' %}

{% endblock %}

{% block main %}
    {% bootstrap_messages %}
{% endblock %}

{% block footer %}
    <!--Footer-part-->
    <div class="row-fluid">
    </div>
    <!--end-Footer-part-->
{% endblock %}

autodeploy/templates/base/form.html
{% extends "base/base_width_left.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block container %}
    {{ block.super }}
    <form action="{{ action|default:'' }}" method="{{ method|default:'POST' }}" class="form-horizontal"
          enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit"
                    class="btn btn-primary col-xs-12 col-md-1 col-md-offset-4">{{ ok|default:'确 定' }}</button>
            <!--         <a href="{{ next }}" class="btn btn-default col-xs-12 col-md-1 col-md-offset-2">{{ cancel|default:'返 回' }}</a> -->
        {% endbuttons %}
    </form>
{% endblock %}
{% block headjs %}{{ form.media }}{% endblock %}
{% block footjs %}
    <!-- 图片上传js -->
    <script src="{% static 'uploadify/uploadimg.js' %}" type="text/javascript"></script>
{% endblock %}

autodeploy/templates/base/form_horizontal.html
{% extends "base/base_width_left.html" %}
{% load bootstrap3 %}
{% block container %}
    {% block headcontent %}{% endblock %}
    <form action="{% block action %}{{ action|default:'' }}{% endblock %}"
          method="{% block method %}{{ method|default:'POST' }}{% endblock %}"
          onsubmit="return {% block onsubmit %}{{ onsubmit|default:'true' }}{% endblock %}" class="form-horizontal"
          enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% block bottomcontent %}
        {% endblock %}
        {% block button %}
            {% buttons %}
                <button type="submit" class="btn btn-primary col-xs-11 col-md-1 col-md-offset-3">{% block okbtn %}保
                    存{% endblock %}</button>
                <!-- 				<a href="{{ next }}" class="btn btn-default col-xs-11 col-md-1 col-md-offset-1">{% block cancelbtn %}{{ cancelbtn|default:'返回' }}{% endblock %}</a> -->
            {% endbuttons %}
        {% endblock %}

    </form>
{% endblock %}
{% block headjs %}{{ form.media }}{% endblock %}